### ISSUE TITLE
The extension stopped working after recent Nightly updates.

### ISSUE THREAD

**Issue by SirNeon618** [m-khvoinitsky/dark-background-light-text-extension#74]
Firefox Nightly 55.0a1 (2017-04-18) (64bit) on Linux

The color changes stopped being applied after April 15th's update IIRC.

**Comment by lotharamious** [comment]
Confirmed broken somewhere between April 8 and April 21 Nightly.  (55.0a1 [2017-04-21] 64-bit on Windows)

**Comment by lotharamious** [comment]
Also broken in Firefox For Android April 21 Nightly.

**Comment by slowriot** [comment]
Still broken on Nightly 55.0a1 (2017-04-22) (64-bit) on Linux - the extension is completely non-functional. Although the menu icon still appears and behaves normally, no change occurs to any page.

**Comment by m-khvoinitsky** [comment]
I't stopped working with 2017-04-16-10-01-36-mozilla-central nightly build.
```
  Message: Module `sdk/remote/lib/process-script.js` is not found at resource://gre/modules/commonjs/sdk/remote/lib/process-script.js
  Stack:
    @resource://gre/modules/commonjs/sdk/remote/child.js:81:3
emitOnObject@resource://gre/modules/commonjs/sdk/event/core.js:110:7
emit@resource://gre/modules/commonjs/sdk/event/core.js:86:38
messageReceived@resource://gre/modules/commonjs/sdk/remote/child.js:67:37
```

**Comment by m-khvoinitsky** [comment]
```
The first bad revision is:
changeset:   353327:6de875ca10a7
user:        Kris Maglione <maglione.k@gmail.com>
date:        Thu Apr 13 15:40:09 2017 -0700
summary:     Bug 1314861: Pre-compute path mapping function to save on runtime lookups. r=ochameau
```

**Comment by m-khvoinitsky** [comment]
Already reported here: https://bugzilla.mozilla.org/show_bug.cgi?id=1358807 - WONTFIX, but there is a workaround - don't use relative path in remoteRequire (which seems obvious from console error - I just hoped that the bug could be fixed upstream) - I'm going to implement it.

**Comment by m-khvoinitsky** [comment]
Fixed in [latest update](https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/versions/?page=1#version-0.5.10)

**Comment by blackwind** [comment]
Not fully fixed, it seems. If you unload a tab (with [Suspend Tab](https://addons.mozilla.org/en-US/firefox/addon/suspend-tab/) or similar), color changes aren't applied when the tab is loaded again.

**Comment by m-khvoinitsky** [comment]
@blackwind, this is not related to the current issue. It's more likely about #45

**Comment by blackwind** [comment]
Gotcha. Only just started happening for me in Firefox 55, so I figured it was this one.
